#Madlib 2

name = input("Enter a name: ")
adjective = input("Enter an adjective: ")
verbing = input("Enter a verb ending in ing: ")
holiday = input("Enter any holiday:")
verb = input("Enter a verb : ")
adverb = input("Enter an adverb: ")
sport = input("Enter a sport: ")
adjectivetwo = input("Enter an adjective: ")
noun = input("Enter a noun")
verbingtwo = input("Enter a verb ending in ing: ")
naturaldisaster = input("Enter a natural disaster: ")
verbtwo = input("Enter a verb (past tense): ")
causeofdeath = input("Enter a cause of death: ")
print("")
print(name + " is on the " + sport + " team, so he is always " + verbing + ".")
print(name + " couldn't wait for " + holiday + ", he always had " + holiday + " merch on, people always said he looked " + adjective + ".")
print("When " + holiday + " finally comes, he grabs his " + adjectivetwo + noun + " and starts " + verbingtwo + ".")
print(name + " ran outside, but he got caught in a " + naturaldisaster + ", he fell down and " + verbtwo)
print(name + " then died of" + causeofdeath)
print("THE END")